-- 激活码表：用于批量生成和管理激活码
-- 在 Supabase SQL Editor 中执行此脚本

CREATE TABLE IF NOT EXISTS activation_codes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  vip_type TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'unused' CHECK (status IN ('unused', 'used')),
  used_by TEXT,
  used_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 允许匿名访问（与已有 users/orders 表一致）
ALTER TABLE activation_codes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all" ON activation_codes
  FOR ALL USING (true) WITH CHECK (true);
